// Homepage FAQ data
export const homepageFAQs = [
    {
        question: "Are ApexWeb3 tools really free? Is there a catch?",
        answer: "Yes, ApexWeb3 tools are completely free with no hidden costs, subscription tiers, or premium features locked behind paywalls. There's no catch. We believe cryptocurrency analysis tools should be accessible to everyone, from beginners to professional traders. Unlike expensive platforms like Nansen ($150/month) or Dune Analytics ($400/month), we provide comprehensive crypto analysis tools at zero cost.\n\nOur business model is based on ethical non-intrusive advertising and carefully selected affiliate partnerships with trusted crypto platforms. We never sell your data, we never require payment for features, and we're committed to keeping these tools free forever. Many users ask why we don't charge, and the answer is simple: we're building a community-first platform where financial barriers don't prevent traders from making informed decisions.\n\nCompare our offering to paid alternatives: full tokenomics analysis, security scanning, portfolio tracking, whale monitoring, and multi-currency conversion—all features that typically cost hundreds per month elsewhere. We sustain operations through display advertising and transparent affiliate partnerships, never compromising the integrity of our analysis or user privacy. Every feature you see today will remain free tomorrow."
    },
    {
        question: "Do I need to connect my wallet or create an account?",
        answer: "Absolutely not. ApexWeb3 tools require zero wallet connections and zero account creation. You can start using every tool immediately—no signup forms, no email verification, no wallet signatures, and no permissions requested. This \"paste-only\" approach is a core security and privacy feature.\n\nMany crypto platforms require wallet connections, which exposes you to significant risks: malicious smart contract approvals, wallet draining attacks, phishing attempts, and unnecessary blockchain bloat from tracking transactions. By never connecting your wallet, you eliminate these risks entirely. When you paste a token address or add portfolio holdings, everything processes locally in your browser—nothing is transmitted to our servers.\n\nThis design philosophy extends to our data storage. Your portfolio holdings, watchlists, and preferences are stored using your browser's localStorage, meaning we literally cannot access your data even if we wanted to. There's no database collecting user information, no analytics tracking your holdings, and no user profiles linking your activity across sessions.\n\nCompare this to wallet-connected platforms like Zerion or Zapper, which require full wallet access to function. While convenient, they can see every token you hold, every transaction you make, and your complete financial history. With ApexWeb3, you maintain complete privacy and security while still accessing professional-grade analysis tools. Your crypto activity is your business alone."
    },
    {
        question: "How accurate is your cryptocurrency price data?",
        answer: "Our price data is sourced directly from CoinGecko's API, one of the most trusted and comprehensive cryptocurrency data aggregators in the industry. CoinGecko aggregates pricing from over 600 cryptocurrency exchanges worldwide, using volume-weighted averaging to provide accurate, reliable prices that reflect true market conditions.\n\nPrice updates occur every 30-60 seconds for all tracked cryptocurrencies, ensuring you're viewing near-real-time data. This refresh rate is ideal for portfolio monitoring, tokenomics analysis, and investment research. For active trading requiring split-second accuracy, we recommend checking prices on your specific exchange, as prices can vary slightly between platforms due to regional premiums, liquidity differences, and exchange-specific supply and demand.\n\nWhy prices might differ from your exchange: First, CoinGecko aggregates global prices while your exchange shows local pricing. Second, low-liquidity tokens may have sparse data points. Third, during extreme volatility or flash crashes, there may be brief delays as data propagates. Fourth, some exchanges have premiums or discounts based on regional demand.\n\nFor 99% of use cases—portfolio tracking, investment decisions, and fundamental analysis—CoinGecko's data is highly accurate and perfectly suitable. We display prices within 1-2% accuracy of real-time exchange rates. If you need exact execution prices for trades, always verify on your chosen exchange before placing orders. CoinGecko's methodology is transparent and trusted by millions of crypto users worldwide, making it the industry standard for price aggregation."
    },
    {
        question: "Which blockchains and cryptocurrencies are supported?",
        answer: "ApexWeb3 tools support all major blockchains and over 10,000 cryptocurrencies through our CoinGecko API integration. This includes every significant blockchain ecosystem: Ethereum (ETH), Binance Smart Chain (BSC), Polygon (MATIC), Solana (SOL), Avalanche (AVAX), Arbitrum, Optimism, Fantom, Cosmos (ATOM), Polkadot (DOT), Cardano (ADA), and many more.\n\nYou can analyze, track, and convert any token listed on CoinGecko, which represents virtually every tradeable cryptocurrency. This includes major coins (Bitcoin, Ethereum, BNB), established altcoins (XRP, ADA, SOL, DOT), DeFi tokens (UNI, AAVE, COMP, SNX), meme coins (DOGE, SHIB, PEPE), stablecoins (USDC, USDT, DAI), and thousands of smaller projects across all chains.\n\nFor the tokenomics analyzer and security scanner, we support any EVM-compatible blockchain (Ethereum, BSC, Polygon, Avalanche, etc.) where smart contracts can be analyzed. Non-EVM chains like Solana may have limited security scanning capabilities due to different contract standards, but price tracking and portfolio management work universally.\n\nNew tokens are automatically available as soon as they're listed on CoinGecko. Serious projects typically get listed within hours or days of launch. If you can't find a token, it likely means it's either extremely new, not yet listed on any tracked exchanges, or hasn't met CoinGecko's listing criteria. You can request token listings directly on CoinGecko's website. This waiting period actually serves as a quality filter—scam tokens often don't bother getting properly listed."
    },
    {
        question: "Is my portfolio data private and secure?",
        answer: "Your privacy is our highest priority. ApexWeb3 tools use a fundamentally different architecture than most crypto platforms: we use local browser storage instead of cloud databases. This means your portfolio data, watchlists, and holdings are stored exclusively on your device using your browser's localStorage API. We literally cannot access your data—we don't have servers collecting this information, no database storing user portfolios, and no backend processing your holdings.\n\nThink of it like writing in a notebook on your desk versus sending that notebook to our office. With local storage, the data never leaves your computer. You can verify this yourself by opening your browser's developer tools and inspecting network traffic—you'll see that portfolio data is never transmitted to our servers. This architectural choice makes it technically impossible for us to see what cryptocurrencies you hold, how much you've invested, or how your portfolio performs.\n\nWe're fully GDPR compliant by design because we don't collect personal data in the first place. No tracking cookies monitor your holdings, no analytics systems record your investments, no user profiles exist on our servers. This is fundamentally more private than platforms like CoinStats or Delta that sync your portfolio across devices, which requires storing your holdings in their databases.\n\nThe privacy tradeoff is that we don't offer automatic cross-device syncing (we're working on an optional encrypted sync feature where you control the decryption keys). For now, if you use multiple devices, we recommend exporting your portfolio as CSV from one device and importing it to another. Clear your browser data and your portfolio is permanently deleted from that device—we can't recover it because we never had it. For maximum privacy on shared computers, use incognito/private browsing mode, though note that data won't persist after closing the browser."
    },
    {
        question: "Can I use these tools on my mobile phone?",
        answer: "Yes! All ApexWeb3 tools are fully responsive and optimized for mobile devices. Whether you're using an iPhone, Android phone, iPad, or any tablet, you'll have access to the complete feature set with an interface designed specifically for smaller screens. We follow a mobile-first design philosophy, meaning tools are built for mobile and enhanced for desktop, not the other way around.\n\nThe mobile experience includes touch-optimized controls, responsive layouts that adapt to screen size, comfortable text sizing for reading on small screens, and efficient data loading that works well on cellular connections. All functionality available on desktop—tokenomics analysis, security scanning, portfolio tracking, whale monitoring, and currency conversion—works identically on mobile devices.\n\nCommon mobile use cases include checking your portfolio performance on the go, scanning a token for security risks before buying at your desk, monitoring whale wallet movements during your commute, quickly converting crypto values while discussing trades, and analyzing tokenomics while researching projects on your phone. The browser-based platform means no app download is required—just visit tools.apexweb3.com on your mobile browser and start using any tool immediately.\n\nFor the best mobile experience, we recommend adding our website to your home screen for app-like access. On iOS, tap the share button and select \"Add to Home Screen.\" On Android, tap the menu and select \"Add to Home Screen.\" This creates an icon on your home screen that opens the tools in a dedicated browser window, providing a native app feel without the storage requirement of a downloaded application."
    },
    {
        question: "How do the investment scores and risk verdicts work?",
        answer: "Our investment scoring system analyzes five key quantitative metrics to generate a 0-100 score representing a token's fundamental strength based on current market data. This is an educational tool, not financial advice—it helps you understand tokenomics and market position but should be combined with qualitative research about team, technology, and adoption.\n\nThe five metrics are weighted as follows: Market Cap Maturity (25 points) - larger market caps indicate established projects with lower volatility risk. Tokenomics Health (25 points) - high circulating supply ratio means lower future dilution. Volatility Score (20 points) - based on price stability and ATH/ATL analysis. Price Performance (20 points) - recent price trends and momentum. Trend Momentum (10 points) - short-term directional strength.\n\nRisk verdicts are categorized based on total scores: Strong Hold (75-100) indicates solid fundamentals, established market position, and lower relative risk—suitable for core portfolio holdings. Speculative (55-74) suggests reasonable fundamentals but higher volatility or uncertainty—monitor closely and size positions appropriately. High Risk (40-54) signals significant concerns like high dilution, small market cap, or unstable tokenomics—only for experienced traders with high risk tolerance. Overvalued (0-39) indicates poor fundamentals, excessive inflation risk, or extreme valuation—generally avoid or wait for major correction.\n\nImportant disclaimers: Scores reflect current state, not future potential. A low score doesn't mean a token will fail—early projects naturally score lower. High scores don't guarantee profits—markets are unpredictable. Our scoring can't evaluate qualitative factors like team quality, technological innovation, partnerships, regulatory risks, or community strength. Use scores as a starting point for research, not a sole decision factor. Past performance never guarantees future results."
    },
    {
        question: "What makes ApexWeb3 different from other crypto tools?",
        answer: "ApexWeb3 stands out through three core differentiators: privacy-first architecture, comprehensive tool integration, and zero-cost access to professional features. Unlike competitors, we've built a platform that prioritizes user privacy without sacrificing functionality, combines multiple essential tools in one ecosystem, and provides institutional-quality analysis free of charge.\n\nPrivacy Architecture: While platforms like Zerion and Zapper require wallet connections to function, ApexWeb3 uses paste-only inputs that eliminate security risks. No wallet signatures, no smart contract approvals, no exposure to draining attacks. Your data stays on your device using local storage—we can't access it even if we wanted to. This is fundamentally different from centralized platforms that store user portfolios in their databases.\n\nIntegrated Tool Suite: CoinGecko offers price tracking. CoinMarketCap provides market data. Tools like RugDoc focus only on security. We integrate tokenomics analysis, security scanning, portfolio tracking, whale monitoring, and currency conversion in one platform. This integration allows workflows like: scan a token for security → analyze its tokenomics → add it to your portfolio → monitor whale movements → track performance over time. All in one place.\n\nFree Professional Features: Nansen charges $150/month for whale tracking. Dune Analytics costs $400/month for custom analysis. We provide comparable functionality at zero cost. No feature limitations, no premium tiers, no paywalls. The same tools available to beginners are available to professionals. This democratizes access to analysis tools that were previously affordable only to institutional investors.\n\nUser Experience: Clean, modern interface designed for speed and clarity. Mobile-optimized for trading on the go. No registration friction—start using tools immediately. Educational approach with detailed explanations, not just raw data. Community-focused rather than profit-maximizing. Continuous improvements based on user feedback."
    }
];
