// Tokenomics Analyzer FAQ data
export const tokenomicsFAQs = [
    {
        question: "What is tokenomics and why should I care?",
        answer: "Tokenomics (token economics) is the study of how a cryptocurrency's supply, distribution, and incentive structures affect its long-term value and price sustainability. Understanding tokenomics is crucial because it reveals whether a token's price can be maintained or is destined to crash regardless of hype or marketing.\n\nThink of tokenomics as the foundation of a building. Great marketing and partnerships are like beautiful paint and furniture, but if the foundation is cracked (bad tokenomics), the building will eventually collapse. Many investors have lost fortunes buying tokens with massive social media followings and celebrity endorsements, only to watch prices crater when the inevitable supply inflation or insider dumps occur.\n\nKey tokenomics factors that affect price: Total Supply determines scarcity—tokens with unlimited supply face constant selling pressure. Circulating Supply Ratio reveals future dilution—if only 10% of tokens are circulating now, 90% will eventually hit the market, diluting your holdings. Vesting Schedules show when large blocks of tokens unlock—team and investor tokens typically unlock gradually, creating selling pressure. Distribution determines decentralization—if top 10 wallets hold 60% of supply, they control price action.\n\nReal-world examples: Bitcoin's fixed 21 million supply creates scarcity driving value. Ethereum's post-merge burning mechanism makes it deflationary, supporting long-term prices. Conversely, Terra/LUNA collapsed partly due to algorithmic tokenomics that created infinite selling pressure. Many 2021 DeFi tokens crashed 90%+ when team vesting unlocked and insiders dumped on retail investors.\n\nIgnoring tokenomics and buying based solely on Twitter hype, Telegram shilling, or influencer promotions is one of the fastest ways to lose money in crypto. Our tokenomics analyzer helps you avoid these traps by revealing the math behind token sustainability. A token with excellent technology but terrible tokenomics is still a poor investment. Conversely, a token with solid tokenomics and mediocre tech often outperforms over time."
    },
    {
        question: "How accurate are the investment scores?",
        answer: "Our investment scores are educational tools based on quantitative metrics, not predictive algorithms or guaranteed indicators of future performance. They're highly accurate at representing current fundamental conditions but cannot predict market sentiment, future developments, or black swan events.\n\nWhat the scores measure accurately: Current market cap maturity (objective data), today's circulating supply ratio (blockchain-verified), recent price volatility (historical data), tokenomics health based on supply metrics (mathematical calculations), relative risk based on dilution factors (formula-driven). These are facts, not predictions.\n\nWhat the scores cannot measure: Future technology breakthroughs, upcoming partnerships or exchange listings, regulatory changes affecting the project, team competence and execution ability, community growth and network effects, competitor developments, macroeconomic market conditions, social media momentum and viral potential.\n\nAccuracy depends on data quality from CoinGecko's API. For well-established tokens (Bitcoin, Ethereum, major altcoins), data is comprehensive and highly accurate. For newer or low-liquidity tokens, data may be incomplete or delayed, affecting score reliability. We recommend using scores as starting points that answer \"What do the current fundamentals look like?\" not \"Should I definitely buy this?\"\n\nBacktesting context: Tokens with Strong Hold verdicts (75-100 scores) historically show better risk-adjusted returns than High Risk tokens, but many High Risk tokens have delivered 10x-100x returns during bull markets. Conversely, some Strong Hold tokens have underperformed during bear markets. Scores reflect safety and fundamental strength, not potential percentage gains.\n\nBest practice: Use investment scores as one input in a multi-factor decision framework. Combine quantitative metrics (our scores) with qualitative research (read whitepaper, research team, check GitHub activity, evaluate use case, assess competition). Never invest based solely on scores or any single metric. Diversify across different score categories aligned with your risk tolerance. Remember that all investments carry risk, and past performance never guarantees future results."
    },
    {
        question: "What's the difference between circulating supply and total supply?",
        answer: "Circulating supply is the number of tokens currently available for trading on markets—these tokens are actively circulating in wallets, exchanges, and DeFi protocols. Total supply is all tokens that will ever exist according to the project's protocol rules or schedule. The difference between these numbers reveals future dilution risk—one of the most important metrics in tokenomics analysis.\n\nWhy this matters: If a token has 10 million circulating supply but 100 million total supply, that means 90 million tokens (90%) are currently locked, vested, or not yet minted. When these tokens eventually enter circulation, they create selling pressure that can crash prices even if demand remains constant. It's simple math: increase supply without increasing demand = lower price.\n\nVesting schedules determine when locked tokens unlock. Team allocations typically vest over 2-4 years to align long-term incentives. Investor allocations (VCs and private sale participants) often have 6-12 month cliff periods then linear vesting. Ecosystem reserves unlock gradually for development funding, marketing, and liquidity incentives. When major vesting events occur (called \"unlock events\"), tokens hit the market creating sell pressure.\n\nReal example: Imagine a token launches at $1 with 10M circulating, reaching $10M market cap. If total supply is 1000M, that's only 1% circulating. When the remaining 99% eventually unlocks, even if each new token sells at the same $1 price, the fully diluted valuation (FDV) would be $1 billion—100x the current market cap. This means either price must 100x to maintain the same FDV/MCap ratio, or (more likely) price crashes as supply floods the market.\n\nMax supply is sometimes different from total supply—max supply is the absolute hard cap (like Bitcoin's 21M), while total supply is current total including burned tokens. Some tokens have no max supply (inflationary models). Always check: circulation ratio (circulating/total), vesting schedules (when do unlocks occur), burn mechanisms (deflationary offset), and emission rates (new token creation speed)."
    },
    {
        question: "What does 'inflation risk' mean in crypto?",
        answer: "Inflation risk in cryptocurrency refers to the dilution of your token holdings' value caused by increasing token supply. Unlike monetary inflation (purchasing power decrease), crypto inflation specifically means more tokens entering circulation faster than demand growth, creating downward price pressure through supply-demand imbalance.\n\nOur inflation risk formula: (Total Supply - Circulating Supply) / Circulating Supply. This calculates how much additional supply will eventually hit the market relative to current circulation. A ratio above 2.0 means future supply will more than double current circulation—a major red flag indicating severe dilution risk.\n\nExample interpretation: Ratio of 0.5 (50%) = moderate inflation, 50% more tokens will circulate. Ratio of 1.0 (100%) = high inflation, supply will double. Ratio of 2.0 (200%) = extreme inflation, supply will triple. Ratio of 5.0+ (500%+) = catastrophic inflation risk, avoid unless you have strong conviction.\n\nNot all inflation is bad: Controlled inflation can fund development (Ethereum's issuance pays for security), incentivize behaviors (staking rewards), and bootstrap networks (liquidity mining). The key is whether inflation is matched by demand growth and value creation. Bitcoin has inflation (new blocks create BTC) but it's predictable, decreasing (halving events), and capped (21M maximum).\n\nProblematic inflation patterns: Unlimited maximum supply with no cap, exponential emission rates that create more tokens over time, team allocation that far exceeds circulating supply, lack of burn mechanisms to offset emissions, vesting schedules with cliff unlocks (large amounts unlocking simultaneously), high emissions promised to early investors as rewards.\n\nEthereum case study: Post-merge Ethereum became deflationary by burning portion of transaction fees. When burn rate exceeds issuance, supply decreases over time, creating scarcity. This is opposite of inflation and supports price appreciation. Other projects with burn mechanisms include BNB (quarterly burns), SHIB (community burns), and various DeFi tokens with buyback-and-burn models.\n\nWhen inflation becomes problematic: If token price isn't keeping pace with supply growth, if team is dumping unlocked tokens regularly, if emissions far exceed usage and adoption metrics, if protocol makes unrealistic promises of perpetual high yields (Ponzi warning sign)."
    },
    {
        question: "Can a token with a low score still be a good investment?",
        answer: "Absolutely yes. Low scores indicate higher current risk based on quantitative metrics, but risk and reward are correlated in investing—higher risk often means higher potential returns. Many tokens that eventually deliver 10x, 50x, or 100x gains start with low scores because they're early-stage, small market cap, or highly volatile.\n\nWhy low scores don't mean zero potential: Early-stage projects naturally score lower (small market cap, high volatility, incomplete tokenomics data). Scores reflect current state, not future potential—a great team executing well can dramatically improve tokenomics over time. Our scoring doesn't measure qualitative factors: innovative technology, strong community, blue-chip partnerships, first-mover advantage, network effects.\n\nHistorical examples: Many successful projects had concerning early tokenomics. Ethereum launched with no maximum supply cap (changed later with EIP-1559). Solana had highly concentrated distribution initially. Numerous DeFi blue chips started as small-cap speculative plays. The difference between tokens that succeed despite low scores and those that fail is execution, adoption, and team competence—factors our quantitative model can't measure.\n\nAppropriate use of low-scoring tokens: Position sizing—risk only capital you can afford to lose completely (maybe 5-10% of crypto portfolio for high-risk positions). Diversification—don't bet everything on one speculative token. Research depth—low scores require extra diligence on team, technology, roadmap, competition. Entry timing—consider dollar-cost averaging rather than lump sum on high volatility assets. Exit planning—set profit targets and stop losses before entering position.\n\nRed flags even for speculative plays: Multiple serious issues (unverified contract + no liquidity lock + anonymous team + honeypot detected). Recent history of rug pulls by contract deployer. Clearly unrealistic promises (\"guaranteed 1000% APY\" = Ponzi). No real product or use case, just promises. These are avoid-at-all-costs situations.\n\nWhen to take calculated risks on low scores: You've researched thoroughly and believe in the project's vision. You understand the specific risks revealed by the score. You're sizing the position appropriately for your risk tolerance. You have conviction based on qualitative factors we don't measure. You're comfortable with potential total loss. Remember: speculation is not investing. High-risk plays should be small portions of a diversified portfolio."
    }
];

// Add more FAQs continued...
export const tokenomicsFAQsContinued = [
    {
        question: "How often should I check a token's score?",
        answer: "Tokenomics scores update with real-time market data, but fundamental conditions change slowly. We recommend different checking frequencies based on investment style:\n\nBefore initial investment: Always check immediately before buying. Tokenomics can change (unlocks, burns, supply updates). Verify fundamentals are acceptable for your risk tolerance.\n\nLong-term holders: Check monthly or quarterly. Major changes are rare but should be monitored—new vesting schedules, tokenomics proposals, burn mechanisms, protocol changes. Set calendar reminders for quarterly reviews.\n\nActive traders: Check before adding to positions or taking profits. Market cap changes affect maturity scores. Price volatility impacts risk assessments. Timing major unlock events requires monitoring.\n\nMajor events trigger checks: Token burns announced, major vesting unlocks scheduled, governance proposals affecting supply, team announcements about tokenomics changes, unexpected price movements (investigate why).\n\nAvoid obsessive monitoring: Checking daily or hourly wastes time and creates emotional decisions. Fundamentals don't change that rapidly. Set price alerts instead of constant manual checking. Focus on qualitative developments (partnerships, product launches) not score fluctuations.\n\nExample monitoring schedule: Research phase (before buying): Check thoroughly. Month 1-6: Check monthly. Month 6+: Check quarterly unless major events occur. Before selling: Final check on current state."
    },
    {
        question: "What does 'Strong Hold' verdict mean for my investment?",
        answer: "A 'Strong Hold' verdict (75-100 score) indicates solid current fundamentals based on our quantitative analysis—this token demonstrates mature market cap, healthy tokenomics, manageable volatility, and positive performance trends. However, this is NOT financial advice to buy or hold, and strong fundamentals don't guarantee profits.\n\nWhat Strong Hold signals: Lower relative risk compared to alternatives. Established market position with significant liquidity. Healthy supply distribution without excessive future dilution. Reasonable volatility patterns. Good foundation for long-term holding.\n\nWhat Strong Hold does NOT guarantee: Future price appreciation (markets are unpredictable). Protection from market-wide crashes (all cryptos correlate during downturns). No competition risks or technological obsolescence. Team will continue executing well. Regulatory environment remains favorable.\n\nAppropriate investor response to Strong Hold: Suitable for core portfolio positions (40-60% of crypto allocation). Lower position sizing risk compared to speculative tokens. Appropriate for risk-averse investors or those new to crypto. Can be held through volatility with more confidence. Still requires periodic review (quarterly recommended).\n\nStill require your judgment: Our scoring can't evaluate upcoming catalysts, pending regulations, competitive threats, team changes, technology risks, market sentiment shifts. A Strong Hold today might face challenges tomorrow. Diversify even among high-scoring tokens.\n\nHistorical perspective: Many Strong Hold tokens underperform during bull market euphoria as speculators chase higher-risk plays. However, they typically show better risk-adjusted returns over full market cycles and protect capital better during bear markets. Think of Strong Hold as defensive positions, not maximum growth plays."
    }
];
