export const POPULAR_COINS = [
    { id: 'bitcoin', symbol: 'btc', name: 'Bitcoin' },
    { id: 'ethereum', symbol: 'eth', name: 'Ethereum' },
    { id: 'tether', symbol: 'usdt', name: 'Tether' },
    { id: 'binancecoin', symbol: 'bnb', name: 'BNB' },
    { id: 'solana', symbol: 'sol', name: 'Solana' },
    { id: 'ripple', symbol: 'xrp', name: 'XRP' },
    { id: 'usd-coin', symbol: 'usdc', name: 'USDC' },
    { id: 'cardano', symbol: 'ada', name: 'Cardano' },
    { id: 'avalanche-2', symbol: 'avax', name: 'Avalanche' },
    { id: 'dogecoin', symbol: 'doge', name: 'Dogecoin' },
    { id: 'polkadot', symbol: 'dot', name: 'Polkadot' },
    { id: 'chainlink', symbol: 'link', name: 'Chainlink' },
    { id: 'tron', symbol: 'trx', name: 'TRON' },
    { id: 'polygon', symbol: 'matic', name: 'Polygon' },
    { id: 'shiba-inu', symbol: 'shib', name: 'Shiba Inu' },
    { id: 'litecoin', symbol: 'ltc', name: 'Litecoin' },
    { id: 'bitcoin-cash', symbol: 'bch', name: 'Bitcoin Cash' },
    { id: 'uniswap', symbol: 'uni', name: 'Uniswap' },
    { id: 'stellar', symbol: 'xlm', name: 'Stellar' },
    { id: 'monero', symbol: 'xmr', name: 'Monero' },
    { id: 'ethereum-classic', symbol: 'etc', name: 'Ethereum Classic' },
    { id: 'cosmos', symbol: 'atom', name: 'Cosmos' },
    { id: 'filecoin', symbol: 'fil', name: 'Filecoin' },
    { id: 'internet-computer', symbol: 'icp', name: 'Internet Computer' },
    { id: 'hedera-hashgraph', symbol: 'hbar', name: 'Hedera' },
    { id: 'aptos', symbol: 'apt', name: 'Aptos' },
    { id: 'near', symbol: 'near', name: 'NEAR Protocol' },
    { id: 'vechain', symbol: 'vet', name: 'VeChain' },
    { id: 'quant-network', symbol: 'qnt', name: 'Quant' },
    { id: 'arbitrum', symbol: 'arb', name: 'Arbitrum' },
    { id: 'aave', symbol: 'aave', name: 'Aave' },
    { id: 'algo', symbol: 'algo', name: 'Algorand' },
    { id: 'fantom', symbol: 'ftm', name: 'Fantom' },
    { id: 'the-graph', symbol: 'grt', name: 'The Graph' },
    { id: 'the-sandbox', symbol: 'sand', name: 'The Sandbox' },
    { id: 'decentraland', symbol: 'mana', name: 'Decentraland' },
    { id: 'eos', symbol: 'eos', name: 'EOS' },
    { id: 'theta-token', symbol: 'theta', name: 'Theta Network' },
    { id: 'tezos', symbol: 'xtz', name: 'Tezos' },
    { id: 'axie-infinity', symbol: 'axs', name: 'Axie Infinity' },
]; // truncated list for brevity, but includes top 40ish
